Official Page link added
Shivansh2407/AWS-Machine-Learning-Foundations-Scholarship pull request #8
Opened 2021-07-04 08:16 UTC by rishabdesai

Only official page links and details added. This can be elaborated.

2021-07-04 10:44 UTC, xxprime requested changes
Hi @rishabdesai, this looks great! I have a couple of suggestions below, kindly check if it's applicable. Thanks!

2021-07-04 10:44 UTC, xxprime commented on Useful Content.md
> +* Official Recommended Course:
Maybe this is better? What do you think?

```suggestion
* Recommended Pre-requisite Courses:
```

2021-07-04 10:44 UTC, xxprime commented on Useful Content.md
> +    * [ Intro to Python Programming](https://www.udacity.com/course/introduction-to-python--ud1110)
```suggestion
    * [Intro to Python Programming](https://www.udacity.com/course/introduction-to-python--ud1110)
```

2021-07-04 10:44 UTC, xxprime commented on Useful Content.md
> +| Challenge End Date | 1-October-2021 |
```suggestion
| Challenge End Date | 11-October-2021 |
```

2021-07-05 00:13 UTC, xxprime approved these changes
Great work @rishabdesai! 💯 

Ship it @Shivansh2407! 🚀

2021-07-05 04:06 UTC, Shivansh2407 approved these changes
Great work @rishabdesai :tada: LGTM :+1:

2021-07-05 04:07 UTC, merged

2021-07-05 04:10 UTC, Shivansh2407 commented
Thank you @rishabdesai for contributing! Keep Contributing :tada: